package livetiming

type DriverList struct {
	Field1 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"44"`
	Field2 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"11"`
	Field3 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"33"`
	Field4 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"16"`
	Field5 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"10"`
	Field6 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"3"`
	Field7 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"4"`
	Field8 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"77"`
	Field9 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"31"`
	Field10 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"18"`
	Field11 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"55"`
	Field12 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"63"`
	Field13 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"5"`
	Field14 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"6"`
	Field15 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"14"`
	Field16 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"7"`
	Field17 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"99"`
	Field18 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"47"`
	Field19 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"9"`
	Field20 struct {
		RacingNumber  string `json:"RacingNumber"`
		BroadcastName string `json:"BroadcastName"`
		FullName      string `json:"FullName"`
		Tla           string `json:"Tla"`
		Line          int    `json:"Line"`
		TeamName      string `json:"TeamName"`
		TeamColour    string `json:"TeamColour"`
		FirstName     string `json:"FirstName"`
		LastName      string `json:"LastName"`
		Reference     string `json:"Reference"`
		HeadshotUrl   string `json:"HeadshotUrl"`
	} `json:"22"`
}
